Do not allocate when natts is 0
**Describe the bug**
Failed to bind the MySQL query when foreign scan will select NULL from an inner join.

**To Reproduce**
1. On MySQL server
DROP DATABASE IF EXISTS join_limit;
CREATE DATABASE join_limit;
USE join_limit;

CREATE TABLE J1_TBL ( i integer, j integer, t text);
CREATE TABLE J2_TBL ( i integer, k integer);
CREATE TABLE J3_TBL ( i integer, t text);

INSERT INTO J1_TBL VALUES (1, 4, 'one');
INSERT INTO J1_TBL VALUES (2, 3, 'two');
INSERT INTO J1_TBL VALUES (3, 2, 'three');
INSERT INTO J1_TBL VALUES (4, 1, 'four');
INSERT INTO J1_TBL VALUES (5, 0, 'five');
INSERT INTO J1_TBL VALUES (6, 6, 'six');
INSERT INTO J1_TBL VALUES (7, 7, 'seven');
INSERT INTO J1_TBL VALUES (8, 8, 'eight');
INSERT INTO J1_TBL VALUES (0, NULL, 'zero');
INSERT INTO J1_TBL VALUES (NULL, NULL, 'null');
INSERT INTO J1_TBL VALUES (NULL, 0, 'zero');

INSERT INTO J2_TBL VALUES (1, -1);
INSERT INTO J2_TBL VALUES (2, 2);
INSERT INTO J2_TBL VALUES (3, -3);
INSERT INTO J2_TBL VALUES (2, 4);
INSERT INTO J2_TBL VALUES (5, -5);
INSERT INTO J2_TBL VALUES (5, -5);
INSERT INTO J2_TBL VALUES (0, NULL);
INSERT INTO J2_TBL VALUES (NULL, NULL);
INSERT INTO J2_TBL VALUES (NULL, 0);

INSERT INTO J3_TBL VALUES (1, 'first');
INSERT INTO J3_TBL VALUES (2, NULL);
INSERT INTO J3_TBL VALUES (2, 'second');
INSERT INTO J3_TBL VALUES (3, 'third');
INSERT INTO J3_TBL VALUES (4, 'forth');
INSERT INTO J3_TBL VALUES (5, 'five');

2. Execute SQL

CREATE FOREIGN TABLE J1_TBL__mysql_svr__0 ( i integer, j integer, t text) SERVER mysql_svr OPTIONS (dbname 'join_limit', table_name 'J1_TBL');
CREATE FOREIGN TABLE J2_TBL__mysql_svr__0 ( i integer, k integer) SERVER mysql_svr OPTIONS (dbname 'join_limit', table_name 'J2_TBL');
CREATE FOREIGN TABLE J3_TBL__mysql_svr__0 ( i integer, t text) SERVER mysql_svr OPTIONS (dbname 'join_limit', table_name 'J3_TBL');

SELECT * FROM j2_tbl__mysql_svr__0 where exists (select t3.i, t from j3_tbl__mysql_svr__0 t3 join j2_tbl__mysql_svr__0 t2 on t2.i = t3.i);

3. Result before fixing
SELECT * FROM j2_tbl__mysql_svr__0 where exists (select t3.i, t from j3_tbl__mysql_svr__0 t3 join j2_tbl__mysql_svr__0 t2 on t2.i = t3.i);
ERROR:  failed to bind the MySQL query

**Result after fixing**
 i | k
---+----
 1 | -1
 2 |  2
 3 | -3
 2 |  4
 5 | -5
 5 | -5
 0 |
   |
   |  0
(9 rows)

**Additional context**
Because with tupleDescriptor->natts = 0 is used to palloc for table->mysql_bind.
But it will return invalid memory like address: 0x7f7f7f7f7f7f7f7f.
With this allocated memory, the binding will fail and it causes error "failed to bind the MySQL query".

When natts is 0, it means the PostgreSQL/PGSpider core does not need any result in tuple slot.
Therefore, no need to allocate memory for festate->table in this case.